from django.urls import path

from .views import (
    ModelSearchView,
    NewsListCreateView,
    NewsDetailView,
    MenuListCreateView,
    MenuDetailView,
    SettingsDetailView,
    HomeListCreateView,
    HomeDetailView,
    AboutListCreateView,
    AboutDetailView,
    AboutExtraListCreateView,
    AboutExtraDetailView,
    SubjectListCreateView,
    SubjectDetailView,
    SubjectSectionListCreateView,
    SubjectSectionDetailView,
    HistoryListCreateView,
    HistoryDetailView,
    ReviewListCreateView,
    ReviewDetailView,
    GalleryListCreateView,
    GalleryDetailView,
    HeaderFooterSettingsListCreateView,
    HeaderFooterSettingsDetailView,
)

urlpatterns = [
    path('search/', ModelSearchView.as_view(), name='search'),
    path('news/', NewsListCreateView.as_view(), name='news-list'),
    path('news/<int:pk>/', NewsDetailView.as_view(), name='news-detail'),
    path('menu/', MenuListCreateView.as_view(), name='menu-list'),
    path('menu/<int:pk>/', MenuDetailView.as_view(), name='menu-detail'),
    path('settings/<int:pk>/', SettingsDetailView.as_view(), name='settings-detail'),
    path('home/', HomeListCreateView.as_view(), name='home-list'),
    path('home/<int:pk>/', HomeDetailView.as_view(), name='home-detail'),
    path('about/', AboutListCreateView.as_view(), name='about-list'),
    path('about/<int:pk>/', AboutDetailView.as_view(), name='about-detail'),
    path('about-extra/', AboutExtraListCreateView.as_view(), name='about-extra-list'),
    path('about-extra/<int:pk>/', AboutExtraDetailView.as_view(), name='about-extra-detail'),
    path('subjects/', SubjectListCreateView.as_view(), name='subject-list'),
    path('subjects/<int:pk>/', SubjectDetailView.as_view(), name='subject-detail'),
    path('subject-sections/', SubjectSectionListCreateView.as_view(), name='subject-section-list'),
    path('subject-sections/<int:pk>/', SubjectSectionDetailView.as_view(), name='subject-section-detail'),
    path('history/', HistoryListCreateView.as_view(), name='history-list'),
    path('history/<int:pk>/', HistoryDetailView.as_view(), name='history-detail'),
    path('reviews/', ReviewListCreateView.as_view(), name='review-list'),
    path('reviews/<int:pk>/', ReviewDetailView.as_view(), name='review-detail'),
    path('gallery/', GalleryListCreateView.as_view(), name='gallery-list'),
    path('gallery/<int:pk>/', GalleryDetailView.as_view(), name='gallery-detail'),
    path('header-footer-settings/', HeaderFooterSettingsListCreateView.as_view(), name='header-footer-settings-list'),
    path('header-footer-settings/<int:pk>/', HeaderFooterSettingsDetailView.as_view(), name='header-footer-settings-detail'),
]
