# Generated by Django 4.2.7 on 2026-03-25 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_street', '0001_initial'),
    ]

    operations = [
    ]
